//! The operations half of the corpus, which is the specification, executed.
//!
//! `tests/corpus/operations/` is hand-written. The numbered files are the edits
//! the numbered revisions in `tests/corpus/revisions/` made to one file, so the
//! two halves describe one history — with a gap at 04, because a merge that
//! changes nothing about a file names no operation document. The unnumbered
//! files belong to no revision and exist to pin one rule each: carriage returns
//! as content, a last line without a terminator, and items that read like the
//! format but are not it.
//!
//! `states/` is the file those numbered revisions were editing, as it stands at
//! each of them. Those are the corpus's first examples where the interesting
//! property is not what the parser accepts but what the replay produces, and
//! they are hand-written for the same reason every other file here is: a
//! fixture generated by the code it checks proves only that the code is
//! consistent with itself.
//!
//! Nothing yet links a revision to its operation documents. That link is the
//! tree, which decision 0007 defers to 0008.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use historica::core::RevisionId;
use historica::format::{Item, OperationDocument, OperationKind, ParseErrorKind, Version, digest};
use historica::replay::{State, replay};

fn corpus() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/corpus/operations")
}

/// Every `name  digest` pair in MANIFEST, which is `shasum -a 256` output.
fn manifest() -> BTreeMap<String, RevisionId> {
    let text = fs::read_to_string(corpus().join("MANIFEST")).expect("MANIFEST is readable");
    text.lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| {
            let (digest, name) = line.split_once("  ").expect("`<digest>  <name>` per line");
            (
                name.to_owned(),
                digest.parse().expect("a digest in the manifest"),
            )
        })
        .collect()
}

fn read(name: &str) -> Vec<u8> {
    fs::read(corpus().join(name)).unwrap_or_else(|_| panic!("{name} is readable"))
}

fn canonical_names() -> Vec<String> {
    manifest()
        .into_keys()
        .filter(|name| name.ends_with(".ops.txt") && !name.starts_with("invalid/"))
        .collect()
}

/// The file as it stands at one revision, read from `states/`.
fn state(name: &str) -> String {
    String::from_utf8(read(&format!("states/{name}.txt"))).expect("a state is UTF-8")
}

fn parse(name: &str) -> OperationDocument {
    OperationDocument::parse(&read(name)).unwrap_or_else(|error| panic!("{name}: {error}"))
}

#[test]
fn the_manifest_describes_the_corpus_on_disk() {
    for (name, expected) in manifest() {
        assert_eq!(digest(&read(&name)), expected, "{name} has drifted");
    }
}

#[test]
fn every_canonical_file_parses() {
    for name in canonical_names() {
        parse(&name);
    }
}

#[test]
fn writing_a_parsed_document_reproduces_its_bytes() {
    // One byte sequence per set of facts, which is what lets the digest cover
    // the file rather than a re-serialised model.
    for name in canonical_names() {
        let bytes = read(&name);
        assert_eq!(
            parse(&name).write(),
            bytes,
            "{name} does not survive a round trip"
        );
    }
}

#[test]
fn a_documents_id_is_the_digest_of_its_file() {
    let manifest = manifest();
    for name in canonical_names() {
        assert_eq!(parse(&name).id(), manifest[&name], "{name}");
    }
}

/// What each invalid file exists to prove. A test that only asserted "this
/// fails" would pass for a parser that rejected everything.
fn expected_failures() -> Vec<(&'static str, ParseErrorKind)> {
    vec![
        (
            "invalid/adjacent-deletes.ops.txt",
            ParseErrorKind::AdjacentDeletes { at: 0, total: 3 },
        ),
        (
            "invalid/carriage-return-in-an-operation.ops.txt",
            ParseErrorKind::CarriageReturnInOperation,
        ),
        (
            "invalid/content-without-operation.ops.txt",
            ParseErrorKind::ContentWithoutOperation { prefix: '+' },
        ),
        (
            "invalid/delete-after-insert.ops.txt",
            ParseErrorKind::DeleteAfterInsert { position: 4 },
        ),
        (
            "invalid/delete-count-disagrees.ops.txt",
            ParseErrorKind::DeleteCountDisagrees {
                stated: 2,
                found: 1,
            },
        ),
        (
            // Decision 0031: a digest of the destroyed state would confirm a
            // guess at what was destroyed.
            "invalid/result-of-forgetting.ops.txt",
            ParseErrorKind::ResultOfForgetting,
        ),
        (
            "invalid/result-before-version-three.ops.txt",
            ParseErrorKind::HeaderNeedsVersion {
                key: "result".to_owned(),
                found: Version::V1,
                needs: Version::V3,
            },
        ),
        (
            "invalid/malformed-result.ops.txt",
            ParseErrorKind::MalformedDigest {
                key: "result",
                found: "not-a-digest".to_owned(),
            },
        ),
        ("invalid/empty-delete.ops.txt", ParseErrorKind::EmptyDelete),
        ("invalid/empty-insert.ops.txt", ParseErrorKind::EmptyInsert),
        (
            "invalid/inserts-at-one-position.ops.txt",
            ParseErrorKind::InsertsAtOnePosition { position: 4 },
        ),
        (
            "invalid/leading-zero-position.ops.txt",
            ParseErrorKind::MalformedNumber {
                found: "03".to_owned(),
            },
        ),
        (
            "invalid/malformed-operation.ops.txt",
            ParseErrorKind::MalformedOperation { keyword: "delete" },
        ),
        (
            "invalid/missing-separator.ops.txt",
            ParseErrorKind::MissingSeparator,
        ),
        (
            "invalid/no-newline-not-last.ops.txt",
            ParseErrorKind::NoNewlineNotLast { prefix: '+' },
        ),
        (
            "invalid/no-newline-without-item.ops.txt",
            ParseErrorKind::NoNewlineWithoutItem,
        ),
        (
            "invalid/no-operations.ops.txt",
            ParseErrorKind::NoOperations,
        ),
        (
            "invalid/operations-out-of-order.ops.txt",
            ParseErrorKind::OperationsOutOfOrder {
                position: 1,
                after: 5,
            },
        ),
        (
            "invalid/overlapping-operations.ops.txt",
            ParseErrorKind::OverlappingOperations { position: 1 },
        ),
        (
            "invalid/unknown-operation.ops.txt",
            ParseErrorKind::UnknownOperation {
                found: "replace 3 1".to_owned(),
            },
        ),
    ]
}

#[test]
fn every_invalid_file_is_refused_for_its_own_reason() {
    for (name, expected) in expected_failures() {
        let error = OperationDocument::parse(&read(name))
            .err()
            .unwrap_or_else(|| panic!("{name} should not parse"));
        assert_eq!(error.kind, expected, "{name} failed for the wrong reason");
    }
}

#[test]
fn the_invalid_directory_is_entirely_covered() {
    let covered = expected_failures()
        .into_iter()
        .map(|(name, _)| name.to_owned())
        .collect::<BTreeSet<_>>();
    let present = manifest()
        .into_keys()
        .filter(|name| name.starts_with("invalid/"))
        .collect::<BTreeSet<_>>();
    assert_eq!(present, covered);
}

#[test]
fn every_refusal_names_a_line_and_a_fix() {
    for (name, _) in expected_failures() {
        let error = OperationDocument::parse(&read(name)).expect_err("an invalid file");
        let rendered = error.to_string();
        assert!(
            rendered.starts_with("line "),
            "{name}: {rendered} does not name a line"
        );
        let (_, fix) = rendered
            .split_once(';')
            .unwrap_or_else(|| panic!("{name}: {rendered} does not say what to do"));
        assert!(!fix.trim().is_empty(), "{name}: the fix is empty");
    }
}

/// The file the root revision created, as a list of items.
fn root_state() -> Vec<Item> {
    let root = parse("01-root.ops.txt");
    assert_eq!(root.operations.len(), 1, "a first version is one insert");
    let operation = &root.operations[0];
    assert_eq!(operation.kind, OperationKind::Insert);
    assert_eq!(operation.at, 0, "a file's first version is `insert 0`");
    operation.items.clone()
}

#[test]
fn every_deleted_item_agrees_with_the_parent_it_was_deleted_from() {
    // The redundancy decision 0007 kept on purpose: a `-` line that disagrees
    // with the parent's actual text is corruption caught at the moment of
    // replay rather than absorbed into a merge. Here the parent is the root,
    // so the check is one a person can also do by eye.
    let parent = root_state();
    for name in [
        "02-concurrent.ops.txt",
        "03-other.ops.txt",
        "05-amended.ops.txt",
    ] {
        for operation in &parse(name).operations {
            if operation.kind != OperationKind::Delete {
                continue;
            }
            for (offset, item) in operation.items.iter().enumerate() {
                assert_eq!(
                    Some(item),
                    parent.get(operation.at + offset),
                    "{name} deletes an item the root never held"
                );
            }
        }
    }
}

#[test]
fn the_amendment_edits_the_region_the_revision_it_supersedes_edited() {
    // Revision 05 amends 02, so the two are versions of one change, and their
    // operation documents differ: two revisions that made byte-identical edits
    // would share one document, which would make them one event.
    let original = parse("02-concurrent.ops.txt");
    let amended = parse("05-amended.ops.txt");
    assert_ne!(original, amended);
    assert_ne!(original.id(), amended.id());

    assert_eq!(original.operations[0], amended.operations[0]);
    assert_eq!(original.operations[1].at, amended.operations[1].at);
    assert_ne!(original.operations[1].items, amended.operations[1].items);
}

#[test]
fn concurrent_revisions_edit_the_file_through_separate_operations() {
    // 02 and 03 are the corpus's concurrent pair. Neither can be read as the
    // other's parent state, which is what makes the merge in decision 0007 a
    // replay rather than an application.
    let one = parse("02-concurrent.ops.txt");
    let other = parse("03-other.ops.txt");
    assert_ne!(one.id(), other.id());

    // 03 spells a replacement the canonical way, minus lines above plus lines
    // at one position; 02 anchors its insert past the run it removed.
    assert_eq!(other.operations[0].kind, OperationKind::Delete);
    assert_eq!(other.operations[1].kind, OperationKind::Insert);
    assert_eq!(other.operations[0].at, other.operations[1].at);
    assert_eq!(one.operations[1].at, one.operations[0].end());
}

#[test]
fn an_items_bytes_are_its_own_and_survive_untouched() {
    // A CRLF file's carriage returns are content, and are kept: decision 0002
    // bans a CR from the format's own lines, and a file under version control
    // is not one of them.
    let crlf = parse("crlf.ops.txt");
    for operation in &crlf.operations {
        for item in &operation.items {
            assert!(item.text.ends_with('\r'), "a CRLF line keeps its return");
            assert!(item.bytes().ends_with(b"\r\n"));
        }
    }

    // A last line without a terminator, on both sides of a replacement.
    let ends = parse("no-newline.ops.txt");
    for operation in &ends.operations {
        let last = operation.items.last().expect("an operation has items");
        assert!(!last.terminated);
        assert!(!last.bytes().ends_with(b"\n"));
    }

    // Items that read like the format are items: exactly one byte is stripped
    // and nothing else is trimmed, unescaped, or normalised.
    let verbatim = parse("verbatim-items.ops.txt");
    let items = &verbatim.operations[0].items;
    let texts: Vec<&str> = items.iter().map(|item| item.text.as_str()).collect();
    assert!(texts.contains(&"historica-v0"));
    assert!(texts.contains(&""));
    assert!(texts.contains(&"insert 4"));
    assert!(texts.contains(&"-not a deletion"));
    assert!(texts.iter().any(|text| text.starts_with("\\ no newline")));
    assert!(texts.contains(&"  padded with spaces  "));
    assert!(texts.iter().any(|text| text.contains('\t')));
    assert!(texts.iter().any(|text| text.contains('\u{1f31b}')));
    assert!(
        items.iter().all(|item| item.terminated),
        "no marker, no unterminated item"
    );
}

#[test]
fn the_root_revision_creates_the_file_the_others_edit() {
    let created = replay([&parse("01-root.ops.txt")]).expect("a first version");
    assert_eq!(created.text(), state("01-root"));
    assert_eq!(created, State::from_text(&state("01-root")));
}

#[test]
fn each_revision_replays_to_the_file_it_left_behind() {
    // Every one of these is a linear chain — the corpus's concurrent pair is
    // concurrent with each other, not with the root — so replay here is
    // application, which is what decision 0007 says the common case costs.
    let root = parse("01-root.ops.txt");
    for name in ["02-concurrent", "03-other", "05-amended"] {
        let document = parse(&format!("{name}.ops.txt"));
        let replayed = replay([&root, &document]).unwrap_or_else(|error| panic!("{name}: {error}"));
        assert_eq!(replayed.text(), state(name), "{name}");
    }
}

#[test]
fn a_state_is_derived_and_the_operations_are_the_authority() {
    // Deleting every materialised file loses nothing: each one comes back
    // byte for byte from the documents that produced it.
    for name in ["01-root", "02-concurrent", "03-other", "05-amended"] {
        assert_eq!(State::from_text(&state(name)).text(), state(name), "{name}");
    }

    // The amendment and the revision it supersedes are two files, which is why
    // the rewrite in the revision corpus was forced rather than cosmetic.
    let root = parse("01-root.ops.txt");
    let original = replay([&root, &parse("02-concurrent.ops.txt")]).expect("02");
    let amended = replay([&root, &parse("05-amended.ops.txt")]).expect("05");
    assert_ne!(original, amended);
    assert_eq!(original.len() + 1, amended.len());
}

#[test]
fn a_document_replayed_against_the_wrong_parent_is_refused() {
    // 02 and 03 are concurrent: neither was written against the other's
    // result, and replaying them as though they were a chain says so rather
    // than quietly producing a file nobody wrote.
    let root = parse("01-root.ops.txt");
    let chain = [
        &root,
        &parse("03-other.ops.txt"),
        &parse("02-concurrent.ops.txt"),
    ];
    let error = replay(chain).expect_err("03 is not 02's parent");
    let rendered = error.to_string();
    let (_, fix) = rendered
        .split_once(';')
        .unwrap_or_else(|| panic!("{rendered} does not say what to do"));
    assert!(!fix.trim().is_empty());
}
