//! The merged half of the corpus: a history a person can replay by hand.
//!
//! `tests/corpus/merged/` is hand-written, like every other corpus, and it is
//! the first one whose merge is legible without an algorithm. Decision 0032
//! removed the cliff: before it, `04-merge` would have held a delta positioned
//! into whatever a correct Fugue implementation produces, and no amount of
//! patience with `shasum` would have replayed `notes.txt` past it. Here the
//! merge states its file whole, by reference, and the rule a reader follows is
//! four lines long:
//!
//! - a file created here is its payload;
//! - a file edited on one line of history is the parent's state with the
//!   document's operations applied;
//! - a file at a merge whose parents agree is that agreed state — which is why
//!   `04-merge` does not mention `README.md`;
//! - a file at a merge whose parents differ is its resolution.
//!
//! `states/` is what each step produces, hand-written for the reason every
//! fixture here is hand-written: one generated by the code it checks proves
//! only that the code agrees with itself.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use historica::core::{FileId, RevisionId};
use historica::format::{ParseErrorKind, ResolutionDocument, digest, is_resolution};
use historica::store::Store;

fn corpus() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/corpus/merged")
}

/// Every `name  digest` pair in MANIFEST, which is `shasum -a 256` output.
fn manifest() -> BTreeMap<String, RevisionId> {
    let text = fs::read_to_string(corpus().join("MANIFEST")).expect("MANIFEST is readable");
    text.lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| {
            let (digest, name) = line.split_once("  ").expect("`<digest>  <name>` per line");
            (
                name.to_owned(),
                digest.parse().expect("a digest in the manifest"),
            )
        })
        .collect()
}

fn read(name: &str) -> Vec<u8> {
    fs::read(corpus().join(name)).unwrap_or_else(|_| panic!("{name} is readable"))
}

/// The file as it stands at one revision, read from `states/`.
fn state(name: &str) -> String {
    String::from_utf8(read(&format!("states/{name}.txt"))).expect("a state is UTF-8")
}

/// The corpus copied into a scratch store, under the names it already has.
fn merged_root(test: &str) -> PathBuf {
    let scratch = Path::new(env!("CARGO_TARGET_TMPDIR")).join(test);
    let _ = fs::remove_dir_all(&scratch);
    let root = scratch.join("history");
    Store::init(&root).expect("a new store");
    for (name, _) in manifest() {
        let Some(directory) = name.split('/').next() else {
            continue;
        };
        if directory == "states" {
            continue;
        }
        let to = root.join(&name);
        fs::create_dir_all(to.parent().expect("a directory")).expect("a directory");
        fs::copy(corpus().join(&name), &to).expect("copying a corpus file");
    }
    root
}

fn merged_store(test: &str) -> Store {
    Store::open(merged_root(test)).expect("reopening the corpus as a store")
}

/// The digest under which one corpus file is filed.
fn id(name: &str) -> RevisionId {
    digest(&read(name))
}

const NOTES: &str = "nrqvtkzlmwyxsptonvqrklmz";
const README: &str = "swtlmnkqvzyrxopwstlnmkqv";

fn file(id: &str) -> FileId {
    id.parse().expect("a file identifier")
}

#[test]
fn the_manifest_describes_the_corpus_on_disk() {
    for (name, expected) in manifest() {
        assert_eq!(digest(&read(&name)), expected, "{name}");
    }
}

#[test]
fn every_canonical_file_parses_and_writes_back_byte_for_byte() {
    // The property every corpus is held to: one byte sequence per document,
    // so the digest names the file rather than a normalisation of it.
    for name in manifest().into_keys() {
        let bytes = read(&name);
        if name.starts_with("invalid/") || name.starts_with("states/") {
            continue;
        }
        if !name.ends_with(".rev.txt") && !name.ends_with(".ops.txt") {
            continue; // a payload is the file itself, and has no grammar
        }
        let written = if name.ends_with(".rev.txt") {
            historica::format::RevisionDocument::parse(&bytes)
                .unwrap_or_else(|error| panic!("{name}: {error}"))
                .write()
        } else if is_resolution(&bytes) {
            ResolutionDocument::parse(&bytes)
                .unwrap_or_else(|error| panic!("{name}: {error}"))
                .write()
        } else {
            historica::format::OperationDocument::parse(&bytes)
                .unwrap_or_else(|error| panic!("{name}: {error}"))
                .write()
        };
        assert_eq!(written, bytes, "{name}");
    }
}

#[test]
fn the_merge_states_its_resolution_and_the_rest_state_operations() {
    // Decision 0032: both grammars are filed as `.ops.txt`, and the body says
    // which one the bytes are held to.
    assert!(
        is_resolution(&read("operations/04-notes.ops.txt")),
        "the merge's document is a resolution"
    );
    for name in [
        "operations/02-notes.ops.txt",
        "operations/03-notes.ops.txt",
        "operations/05-notes.ops.txt",
    ] {
        assert!(!is_resolution(&read(name)), "{name} states positions");
    }

    let resolution =
        ResolutionDocument::parse(&read("operations/04-notes.ops.txt")).expect("a resolution");
    // Writing it back reproduces the bytes, which is what lets the digest
    // cover the file rather than a normalisation of it.
    assert_eq!(resolution.write(), read("operations/04-notes.ops.txt"));
    // One line the person wrote while resolving, and the rest by reference.
    assert_eq!(resolution.minted(), 1);
    assert_eq!(
        resolution.result,
        Some(digest(state("04-merge").as_bytes()))
    );
}

#[test]
fn every_revision_materialises_to_the_state_written_beside_it() {
    let store = merged_store("merged-states");
    let notes = file(NOTES);
    for (revision, at) in [
        ("01-root", "01-root"),
        ("02-left", "02-left"),
        ("03-right", "03-right"),
        ("04-merge", "04-merge"),
        ("05-after", "05-after"),
    ] {
        let head = id(&format!("revisions/{revision}.rev.txt"));
        assert_eq!(
            store
                .content(&head, &notes)
                .unwrap_or_else(|error| panic!("{revision}: {error}"))
                .text(),
            state(at),
            "{revision}"
        );
    }
}

#[test]
fn a_merge_whose_parents_agree_states_nothing_and_the_file_is_that_state() {
    let store = merged_store("merged-agreed");
    let merge = id("revisions/04-merge.rev.txt");
    let document = store.get(&merge).expect("the merge");
    // The whole of the shortcut, in one assertion: the merge's `edit` lines
    // name `notes.txt` and nothing else.
    assert!(!document.edited.contains_key(&file(README)));
    assert_eq!(
        store
            .content(&merge, &file(README))
            .expect("a file both parents agree about")
            .text(),
        state("README")
    );
}

#[test]
fn the_walk_crossing_the_resolution_agrees_with_following_it() {
    // Decision 0032 demotes the event-graph merge to proposing, and the two
    // must still say one thing about every history they can both express:
    // `content` follows references, `merged_content` walks.
    let store = merged_store("merged-walk");
    let notes = file(NOTES);
    for revision in ["04-merge", "05-after"] {
        let head = id(&format!("revisions/{revision}.rev.txt"));
        assert_eq!(
            store.merged_content(&head, &notes).expect("a walk").state,
            store.content(&head, &notes).expect("a reference"),
            "{revision}"
        );
    }
}

#[test]
fn a_reader_assembles_the_merge_from_the_documents_it_names() {
    // What a person does by hand: open each document the resolution names,
    // count out the run, concatenate, and `shasum` the result. Nothing here
    // touches the event graph.
    let store = merged_store("merged-by-hand");
    let assembled: String = [
        (id("operations/01-notes.txt"), 0, 1),
        (id("operations/02-notes.ops.txt"), 0, 1),
        (id("operations/01-notes.txt"), 1, 1),
    ]
    .into_iter()
    .map(|(document, first, count)| {
        let items = store
            .minted(&document)
            .expect("a document this store holds")
            .expect("a document that mints items");
        items[first..first + count]
            .iter()
            .map(|item| format!("{}\n", item.text))
            .collect::<String>()
    })
    .chain(["foxtrot\n".to_owned()])
    .chain(std::iter::once({
        let items = store
            .minted(&id("operations/03-notes.ops.txt"))
            .expect("a document this store holds")
            .expect("a document that mints items");
        format!("{}\n", items[0].text)
    }))
    .collect();
    assert_eq!(assembled, state("04-merge"));
    assert_eq!(
        digest(assembled.as_bytes()),
        ResolutionDocument::parse(&read("operations/04-notes.ops.txt"))
            .expect("a resolution")
            .result
            .expect("a resolution this tool wrote states its result")
    );
}

#[test]
fn the_corpus_is_a_store_that_checks_clean() {
    let report = Store::check(merged_root("merged-check"));
    let errors: Vec<String> = report.errors().map(ToString::to_string).collect();
    assert!(errors.is_empty(), "{errors:#?}");
}

/// The merged corpus as a store, stopping at the merge, with the resolution
/// and the merge document put through `resolution` and `merge` on the way in.
///
/// Editing either moves the merge's digest, so `05-after` — which names it as
/// a parent — is left out rather than rewritten. Every check below wants a
/// store that is the corpus in exactly one respect other than this.
fn tampered(
    test: &str,
    keep: &[&str],
    resolution: impl FnOnce(String) -> String,
    merge: impl FnOnce(String) -> String,
) -> PathBuf {
    let scratch = Path::new(env!("CARGO_TARGET_TMPDIR")).join(test);
    let _ = fs::remove_dir_all(&scratch);
    let root = scratch.join("history");
    Store::init(&root).expect("a new store");
    for name in keep {
        let to = root.join(name);
        fs::create_dir_all(to.parent().expect("a directory")).expect("a directory");
        fs::copy(corpus().join(name), &to).expect("copying a corpus file");
    }

    let was = id("operations/04-notes.ops.txt");
    let text = resolution(
        String::from_utf8(read("operations/04-notes.ops.txt")).expect("a resolution is UTF-8"),
    );
    fs::write(root.join("operations/04-notes.ops.txt"), &text).expect("the resolution");
    let now = digest(text.as_bytes());

    let document =
        merge(String::from_utf8(read("revisions/04-merge.rev.txt")).expect("a revision is UTF-8"))
            .replace(&was.to_string(), &now.to_string());
    fs::write(root.join("revisions/04-merge.rev.txt"), document).expect("the merge");
    root
}

/// Everything the corpus holds up to and excluding the merge.
const BEFORE_THE_MERGE: &[&str] = &[
    "operations/01-notes.txt",
    "operations/01-readme.md",
    "operations/02-notes.ops.txt",
    "operations/03-notes.ops.txt",
    "revisions/01-root.rev.txt",
    "revisions/02-left.rev.txt",
    "revisions/03-right.rev.txt",
];

fn findings(root: &Path) -> Vec<String> {
    Store::check(root)
        .findings()
        .iter()
        .map(ToString::to_string)
        .collect()
}

/// Decision 0032, both directions at once: the resolution is moved onto the
/// file both parents agree about, which leaves the file they disagree about
/// with nothing stated for it.
#[test]
fn a_merge_owes_a_resolution_where_its_parents_differ_and_nowhere_else() {
    let root = tampered(
        "merged-misplaced",
        BEFORE_THE_MERGE,
        |text| text,
        |text| text.replace(&format!("edit {NOTES} "), &format!("edit {README} ")),
    );
    let report = Store::check(&root);
    let errors: Vec<String> = report.errors().map(ToString::to_string).collect();
    let notes: Vec<String> = report.notes().map(ToString::to_string).collect();
    assert!(
        errors
            .iter()
            .any(|finding| finding.contains("both its parents leave exactly the same")),
        "a resolution where there was nothing to resolve: {errors:#?}"
    );
    assert!(
        notes
            .iter()
            .any(|finding| finding.contains("states no resolution")),
        "and nothing stated where there was: {notes:#?}"
    );
}

/// A resolution is not self-contained prose, and this is one of the documents
/// it names not having arrived.
#[test]
fn a_keep_of_a_document_nothing_holds_is_a_note() {
    let held: Vec<&str> = BEFORE_THE_MERGE
        .iter()
        .copied()
        .filter(|name| *name != "operations/01-notes.txt")
        .collect();
    let root = tampered("merged-undelivered", &held, |text| text, |text| text);
    let report = Store::check(&root);
    assert!(
        report
            .notes()
            .any(|finding| finding.to_string().contains("keeps items of")),
        "{:#?}",
        findings(&root)
    );
    assert!(
        report
            .errors()
            .all(|finding| !finding.to_string().contains("keeps items of")),
        "an undelivered document is ordinary, not a contradiction"
    );
}

/// A run longer than the document it names has items is the store
/// contradicting itself, and no amount of syncing fixes it.
#[test]
fn a_keep_past_the_end_of_its_document_is_an_error() {
    let root = tampered(
        "merged-overrun",
        BEFORE_THE_MERGE,
        |text| {
            let notes = id("operations/01-notes.txt");
            text.replace(&format!("keep {notes} 1 1"), &format!("keep {notes} 1 9"))
        },
        |text| text,
    );
    let errors: Vec<String> = Store::check(&root)
        .errors()
        .map(ToString::to_string)
        .collect();
    assert!(
        errors.iter().any(|finding| finding.contains("which mints")),
        "{errors:#?}"
    );
}

/// Decision 0031 is what 0032 landed second for: a hand-assembled resolution
/// is verified by `shasum` like everything else.
#[test]
fn a_resolution_that_does_not_assemble_to_its_result_is_an_error() {
    let root = tampered(
        "merged-lying-result",
        BEFORE_THE_MERGE,
        |text| text.replace("+foxtrot", "+something else entirely"),
        |text| text,
    );
    let errors: Vec<String> = Store::check(&root)
        .errors()
        .map(ToString::to_string)
        .collect();
    assert!(
        errors
            .iter()
            .any(|finding| finding.contains("and replaying it produces")),
        "{errors:#?}"
    );
}

/// The corpus is not a fixture somebody generated: it is what an editor and a
/// checksum program print.
///
/// `tests/by-hand.sh` is decision 0032's tool-less merge as a list of
/// commands, and what it builds is this directory, byte for byte. Holding the
/// two together is what keeps the corpus honest — a hand-written fixture that
/// quietly stopped being writable by hand would prove nothing.
#[test]
fn the_corpus_is_what_an_editor_and_a_checksum_produce() {
    let scratch = Path::new(env!("CARGO_TARGET_TMPDIR")).join("by-hand-corpus");
    let _ = fs::remove_dir_all(&scratch);
    fs::create_dir_all(&scratch).expect("a scratch directory");
    let script = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/by-hand.sh");
    let built = std::process::Command::new("sh")
        .arg(&script)
        .arg(scratch.join("history"))
        .output()
        .expect("a shell");
    assert!(
        built.status.success(),
        "{}",
        String::from_utf8_lossy(&built.stderr)
    );

    let written: BTreeMap<String, RevisionId> = manifest()
        .into_keys()
        .filter(|name| name.starts_with("revisions/") || name.starts_with("operations/"))
        .map(|name| {
            let bytes = fs::read(scratch.join("history").join(&name))
                .unwrap_or_else(|_| panic!("the script wrote {name}"));
            (name, digest(&bytes))
        })
        .collect();
    for (name, produced) in &written {
        assert_eq!(digest(&read(name)), *produced, "{name}");
    }
    assert_eq!(written.len(), 11, "one file per document in the corpus");
}

/// The store carries the description of itself that makes "readable without
/// the tool" true, so the examples in it are corpus files rather than prose
/// somebody typed and nobody checked again.
#[test]
fn the_format_a_store_explains_itself_with_quotes_the_corpus_verbatim() {
    let explained = historica::store::FORMAT_NOTE;
    for name in [
        "revisions/01-root.rev.txt",
        "operations/03-notes.ops.txt",
        "operations/04-notes.ops.txt",
    ] {
        let text = String::from_utf8(read(name)).expect("a corpus file is UTF-8");
        // Indented by two, and blank lines left blank rather than indented.
        let quoted: String = text
            .lines()
            .map(|line| {
                if line.is_empty() {
                    "\n".to_owned()
                } else {
                    format!("  {line}\n")
                }
            })
            .collect();
        assert!(explained.contains(&quoted), "{name} is not quoted as it is");
    }

    // And every digest it prints is one this corpus actually holds, so a
    // reader following the example lands on the file it names.
    let held: BTreeMap<RevisionId, String> = manifest()
        .into_iter()
        .map(|(name, digest)| (digest, name))
        .collect();
    for word in explained.split(|c: char| !c.is_ascii_hexdigit()) {
        if word.len() != 64 {
            continue;
        }
        let digest: RevisionId = word.parse().expect("64 hexadecimal characters");
        assert!(held.contains_key(&digest), "{word} names nothing here");
    }
}

#[test]
fn every_invalid_resolution_is_refused_for_its_own_reason() {
    for (name, wanted) in invalid() {
        let bytes = read(&format!("invalid/{name}"));
        let error = ResolutionDocument::parse(&bytes)
            .map(|document| document.write())
            .expect_err(&format!("{name} should be refused"));
        assert_eq!(
            std::mem::discriminant(&error.kind),
            std::mem::discriminant(&wanted),
            "{name}: refused as {:?}, wanted {wanted:?}",
            error.kind
        );
    }
}

/// One invalid spelling per rule the grammar pins.
fn invalid() -> Vec<(&'static str, ParseErrorKind)> {
    vec![
        ("adjacent-keeps.ops.txt", ParseErrorKind::AdjacentKeeps),
        ("adjacent-inserts.ops.txt", ParseErrorKind::AdjacentInserts),
        ("empty-keep.ops.txt", ParseErrorKind::EmptyKeep),
        ("empty-insert.ops.txt", ParseErrorKind::EmptyInsert),
        ("no-pieces.ops.txt", ParseErrorKind::NoOperations),
        (
            "insert-with-position.ops.txt",
            ParseErrorKind::ResolutionInsertWithPosition {
                found: String::new(),
            },
        ),
        (
            "keep-without-result.ops.txt",
            ParseErrorKind::MissingHeader { key: "result" },
        ),
        (
            "malformed-keep.ops.txt",
            ParseErrorKind::UnknownOperation {
                found: String::new(),
            },
        ),
        (
            "malformed-keep-digest.ops.txt",
            ParseErrorKind::MalformedDigest {
                key: "keep",
                found: String::new(),
            },
        ),
    ]
}
