//! The two things a writer cannot derive: a clock and a random source.
//!
//! Decision 0010 makes both inputs rather than calls: "a property test that
//! mints identifiers has to be reproducible when it fails, and a corpus that
//! pins a writer's bytes cannot be generated by something that reads a clock."
//! [`Platform`] is what a person's command line uses; a test supplies its own.

use std::fmt;

use crate::core::{ChangeId, FileId};
use crate::format::Timestamp;

/// What time it is, in the offset the answer carries.
pub trait Clock {
    /// The moment now, spelled as the format spells it.
    fn now(&self) -> Result<Timestamp, SourceError>;
}

/// Where 96-bit identifiers come from.
pub trait Entropy {
    /// Fill `bytes` with values nothing can predict and nothing remembers.
    fn fill(&mut self, bytes: &mut [u8]) -> Result<(), SourceError>;

    /// A change nobody has recorded before.
    fn change(&mut self) -> Result<ChangeId, SourceError> {
        let mut bytes = [0u8; crate::core::CHANGE_ID_LEN];
        self.fill(&mut bytes)?;
        Ok(ChangeId::from_bytes(bytes))
    }

    /// A file nobody has recorded before.
    fn file(&mut self) -> Result<FileId, SourceError> {
        let mut bytes = [0u8; crate::core::FILE_ID_LEN];
        self.fill(&mut bytes)?;
        Ok(FileId::from_bytes(bytes))
    }
}

/// The operating system, which is where both of these actually live.
#[derive(Debug, Clone, Copy, Default)]
pub struct Platform;

impl Clock for Platform {
    /// The system clock, in the offset the platform reports for that instant.
    ///
    /// Formatted and then parsed back through the format's own validator, so a
    /// writer cannot emit a timestamp a reader would refuse. Decision 0010
    /// chose `jiff` for the offset because `std` has the instant and not the
    /// zone, and `#![forbid(unsafe_code)]` rules out asking the C library.
    fn now(&self) -> Result<Timestamp, SourceError> {
        let now = jiff::Zoned::now();
        // Seconds are truncated, never rounded: `%S` drops the fraction.
        let spelled = now.strftime("%Y-%m-%dT%H:%M:%S%:z").to_string();
        spelled.parse().map_err(|_| SourceError::Clock { spelled })
    }
}

impl Entropy for Platform {
    fn fill(&mut self, bytes: &mut [u8]) -> Result<(), SourceError> {
        // No fallback. Decision 0010: a weaker source would be exactly the
        // invisible difference in provenance this project avoids.
        getrandom::fill(bytes).map_err(|error| SourceError::Entropy {
            because: error.to_string(),
        })
    }
}

/// A clock or a random source that could not answer.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum SourceError {
    /// The platform produced a time this format cannot spell.
    Clock {
        /// What it produced.
        spelled: String,
    },
    /// The operating system's random source refused.
    Entropy {
        /// What it said.
        because: String,
    },
}

impl fmt::Display for SourceError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SourceError::Clock { spelled } => write!(
                f,
                "this machine's clock reads `{spelled}`, which is not a time \
                 this format can hold"
            ),
            SourceError::Entropy { because } => write!(
                f,
                "the operating system's random source refused, so no change ID \
                 can be minted: {because}"
            ),
        }
    }
}

impl std::error::Error for SourceError {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_platform_clock_spells_a_timestamp_this_format_holds() {
        let now = Platform.now().expect("a clock");
        assert_eq!(now.as_str().len(), 25);
        assert!(now.as_str().contains('T'));
    }

    #[test]
    fn minting_twice_mints_twice() {
        let mut platform = Platform;
        assert_ne!(
            platform.change().expect("a change ID"),
            platform.change().expect("a change ID")
        );
    }
}
