//! `historica-pinned`: `historica` with its clock and its random source fixed.
//!
//! Decision 0010 makes the time and the identifiers a writer mints inputs
//! rather than calls, because "a corpus that pins a writer's bytes cannot be
//! generated by something that reads a clock". The library has always taken
//! them that way; this program is the command line doing the same, so that a
//! second implementation of the writer can be held to the bytes this one puts
//! on disk. It is built only with `--features pinned` and is never installed:
//! the minting below is exactly the predictable source decision 0010 refuses
//! to fall back to, and `historica` itself has no way to ask for it.
//!
//! Two variables, both required, so that a test that forgot one fails rather
//! than quietly recording the real time:
//!
//! - `HISTORICA_PINNED_NOW` is the moment every command reads, spelled as the
//!   format spells one (`2026-01-02T03:04:05+00:00`).
//! - `HISTORICA_PINNED_SEED` is any text. The bytes minted are the SHA-256 of
//!   the seed's bytes followed by a block counter, eight bytes big-endian and
//!   starting at zero, one digest after another, so identifiers come out in
//!   the order the writer asks for them — which is part of what a second
//!   implementation is held to.

mod cli;

use std::process::ExitCode;

use historica::format::Timestamp;
use historica::record::{Clock, Entropy, SourceError};
use sha2::{Digest as _, Sha256};

/// The fixed moment and the seeded stream.
struct Pinned {
    now: Timestamp,
    seed: Vec<u8>,
    block: u64,
    held: Vec<u8>,
}

impl Clock for Pinned {
    fn now(&self) -> Result<Timestamp, SourceError> {
        Ok(self.now.clone())
    }
}

impl Entropy for Pinned {
    fn fill(&mut self, bytes: &mut [u8]) -> Result<(), SourceError> {
        for byte in bytes {
            if self.held.is_empty() {
                let mut hash = Sha256::new();
                hash.update(&self.seed);
                hash.update(self.block.to_be_bytes());
                self.block += 1;
                // Reversed so that `pop` hands the digest out front first.
                self.held = hash.finalize().iter().rev().copied().collect();
            }
            *byte = self.held.pop().expect("a block just drawn");
        }
        Ok(())
    }
}

fn pinned() -> Result<Pinned, String> {
    let variable = |name: &str| {
        std::env::var(name)
            .map_err(|_| format!("`{name}` is not set, and this build reads nothing else"))
    };
    let now = variable("HISTORICA_PINNED_NOW")?;
    let now = now
        .parse()
        .map_err(|error| format!("`HISTORICA_PINNED_NOW` is `{now}`: {error}"))?;
    Ok(Pinned {
        now,
        seed: variable("HISTORICA_PINNED_SEED")?.into_bytes(),
        block: 0,
        held: Vec::new(),
    })
}

fn main() -> ExitCode {
    match pinned() {
        Ok(mut platform) => cli::main(&mut platform),
        Err(message) => {
            eprintln!("historica-pinned: {message}");
            ExitCode::from(2)
        }
    }
}
